nat-tmp

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,84 +1,53 @@
 #!/bin/bash
 
+function printHelp {
+    if [ -n "$2" ]; then
+        echo "ERROR: $2"
+        echo ""
+    fi
+    echo 
+    echo "Usage:"
+    echo "  $1 [-e interface|--external-if=interface]"
+    echo ""
+    echo "-e|--external-if"
+    echo "      External interface for communicating with the outside world. Usually your primary network interface"
+    exit 1
+}
+
 netemFolder=$(realpath $(dirname $0))
 certFolder=$netemFolder/certs
 configFolder=$netemFolder/config
 
 # Handle in-arguments
-for i in "$@"
+externalIf=false
+
+while [[ $# -gt 0 ]] && [[ ."$1" = .--* ]] ;
 do
-    case $i in
-        # Don't create certs (time consuming)
-        -c|--no-certs)
+    opt="$1";
+    shift;              #expose next argument
+    case "$opt" in
+        "--" ) break 2;;
+        "-c"|"--no-certs")
             noCerts=true
-            shift # past argument=value
             ;;
+        "--e")
+            externalIf="$1"
+            shift
+            ;;
+        "--external-if=*")
+            externalIf="${opt#*=}"
+            ;;
+        *) echo >&2 "Invalid option: $@"; exit 1;;
     esac
 done
 
-# --------------------- Cert generation 
-mkdir -p $certFolder
-if [ "$noCerts" != true ];then
-    # Generate a self-signed certificate for encryption
-    openssl req -x509 -newkey rsa:4096 -keyout $certFolder/key.pem -out $certFolder/cert.pem -days 10 -nodes -subj "/C=SE/L=Linkoping/O=Linkoping University/OU=Org/CN=example.com"
-    
-    # Generate more secure dhparams
-    openssl dhparam -out $certFolder/dhparam.pem 2048
+if [ "$externalIf" = false ]; then
+    printHelp $0 "Please choose an external interface!"
 fi
 
-# --------------------- nginx config
-# Create root folder for data and a log folder
+# Create log folder
 logFolder=$netemFolder/logs
-webRoot=$netemFolder/webroot
-mkdir -p $webRoot
 mkdir -p $logFolder
-
-# Create an nginx conf for HTTP and HTTP/2 
-nginxConf=$configFolder/netem.nginx.conf
-cat > $nginxConf << _EOF_
-
-user $USER;
-worker_processes auto;
-pid /tmp/netem.server.pid;
-
-events {
-	worker_connections 768;
-	# multi_accept on;
-}
-
-http {
-    server {
-        listen 443;
-        server_name example.com www.example.com;
-        
-        ssl_certificate $certFolder/cert.pem;
-        ssl_certificate_key $certFolder/key.pem;
-        ssl_dhparam $certFolder/dhparam.pem;
-    
-        root $webRoot;
-    
-        error_log $logFolder/nginx.error.log;
-        access_log $logFolder/nginx.access.log;
-    
-        include $configFolder/tls.conf;
-        include $configFolder/nginx.commons;
-    }
-}
-_EOF_
-
-# --------------------- Caddy config
-caddyFile=$configFolder/netem.Caddyfile
-touch $caddyFile
-
-cat > $caddyFile << _EOF_
-example.com:443
-root $webRoot
-gzip
-log $logFolder/netem.caddy.log
-tls $certFolder/cert.pem $certFolder/key.pem
-
-_EOF_
-
 
 # -------------------- Virtual network setup
 # Setup network namespaces and infrastructure
